version: '2'
services:
    db:
        image: mariadb:10.3
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_RANDOM_ROOT_PASSWORD=1"
        volumes:
            - /etc/localtime:/etc/localtime:ro


    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - $LISTEN_PMA:80
        environment:
            - "PMA_HOST=db"

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"

    app:
        build:
            context: ./docker/app
            args:
                - XDEBUG
        working_dir: /var/www/app
        user: $CONTAINER_USER
        links:
            - db
            - elastic
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./docker/app/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./:/var/www/app:rw

    web:
        image: nginx
        ports:
            - $LISTEN_WEB:80
        links:
            - app
        volumes:
          - ./docker/web/app.conf:/etc/nginx/conf.d/app.conf:ro
        volumes_from:
            - app

volumes:
    esdata:
        driver: local